name: Deploy Windows
description: Build, sign, and upload workflow artifacts for later attachment to the GitHub release
inputs:
  build-identifier:
    description: 'The build identifier (e.g., beta or prod)'
    required: true
  gcp-keyring-path:
    description: 'The path to the GCP keyring'
    required: true
  gcp-key-name:
    description: 'The name of the GCP key'
    required: true
  identity-provider:
    description: 'The identity provider for Google Cloud authentication'
    required: true
  service-account-email:
    description: 'The service account email for Google Cloud authentication'
    required: true

runs:
  using: composite
  steps:
    - name: 📦 Setup PNPM
      uses: pnpm/action-setup@v6
      with:
        version: 11

    - name: ⎔ Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: 📥 Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: 📦 Cache CNG Provider
      id: cache-cng
      uses: actions/cache@v5
      with:
        path: C:\Users\runneradmin\AppData\Local\Temp\KmsCngInstall
        key: cng-provider-v1.3-windows

    - name: 🏗️ Install Google Cloud KMS Provider
      shell: pwsh
      run: .\build\install-kms.ps1
      env:
        CACHE_HIT: ${{ steps.cache-cng.outputs.cache-hit }}

    - name: 🗝️ Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v3
      with:
        access_token_scopes: 'openid, https://www.googleapis.com/auth/cloudkms, https://www.googleapis.com/auth/cloud-platform'
        token_format: 'access_token'
        workload_identity_provider: ${{ inputs.identity-provider }}
        service_account: ${{ inputs.service-account-email }}
        create_credentials_file: true

    - name: 🚀 Build Squirrel distributables
      shell: bash
      run: pnpm run make:squirrel
      env:
        NODE_ENV: production
        GCP_KEYRING_PATH: ${{ inputs.gcp-keyring-path }}
        GCP_KEY_NAME: ${{ inputs.gcp-key-name }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        VITE_IS_BETA: ${{ inputs.build-identifier == 'beta' }}

    - name: 🚀 Build WiX distributables
      shell: bash
      run: pnpm run make:wix
      env:
        NODE_ENV: production
        GCP_KEYRING_PATH: ${{ inputs.gcp-keyring-path }}
        GCP_KEY_NAME: ${{ inputs.gcp-key-name }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        VITE_IS_BETA: ${{ inputs.build-identifier == 'beta' }}

    - name: ⬆️ Upload Windows distributables
      uses: actions/upload-artifact@v7
      with:
        name: windows-release-assets
        path: out/${{ inputs.build-identifier }}/make/
        if-no-files-found: error
