name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'style'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
  default: patch
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
