name: Feature Request
description: File a feature request
title: '[Request]: '
labels: ['enhancement', 'triage']
assignees:
  - steveoh
  - stdavis
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please [search](https://github.com/agrc/api-client/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Aenhancement+is%3Aopen+) to see if an issue already exists for the feature you are wanting.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
