name: deploy
on:
  release:
    types: [published]
jobs:
  version:
    name: NPM Version
    runs-on: ubuntu-latest
    steps:
      - name: Set up code
        uses: actions/checkout@v2

      - name: Update semantic version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Version Bot"
          git config user.email "version-bot@users.noreply.github.com"
          npm version $(gh release view --json tagName --jq ".tagName") -m "release: %s" --allow-same-version
          git push --follow-tags

  macos:
    name: Draft Release
    runs-on: macos-latest
    needs: version
    environment:
      name: prod
    steps:
      - name: Set up code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm

      - name: Set up signing certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

      - name: Install dependencies
        run: npm ci

      - name: Build, Package, & Release
        run: npm run publish
        env:
          APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}
          APPLE_BUNDLE_ID: ${{ secrets.APPLE_BUNDLE_ID }}
          APPLE_USER_ID: ${{ secrets.APPLE_USER_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows:
    name: Draft Release
    runs-on: windows-latest
    needs: version
    environment:
      name: prod
    steps:
      - name: Set up code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build, Package, & Release
        run: npm run publish
        env:
          WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
