on:
  push:
    branches:
      - main

jobs:
  build:
    name: Draft Release
    runs-on: macos-latest
    environment:
      name: prod
    steps:
      - name: Set up code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm

      - name: Set up signing certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: NPM Install
        run: npm ci

      - name: Build, Package, & Release
        run: npm run publish
        env:
          APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}
          APPLE_BUNDLE_ID: ${{ secrets.APPLE_BUNDLE_ID }}
          APPLE_USER_ID: ${{ secrets.APPLE_USER_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
