name: Pull Request Events

on: pull_request

permissions:
  contents: write
  id-token: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-lint:
    name: 🧶 Lint
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v7
        with:
          show-progress: false

      - name: 📦 Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: 📥 Download dependencies
        run: pnpm install --frozen-lockfile

      - name: 🧶 Lint
        run: pnpm lint

      - name: ✔︎ Check Types
        run: pnpm check
