name: Release Drafter
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/**/*.yml'
      - '*.js'
      - '*.json'
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update release notes
        uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
