name: Release Events

on:
  release:
    types: [published]

permissions:
  id-token: write
  deployments: write
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_IDENTIFIER: ${{ github.event.release.prerelease && 'beta' || 'prod' }}

jobs:
  deploy-macos-prod:
    name: Publish macOS app
    if: ${{ !github.event.release.prerelease }}
    runs-on: macos-latest
    environment:
      name: prod
    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6

      - name: 🚀 Deploy macOS app
        uses: ./.github/actions/deploy-macos
        with:
          build-identifier: ${{ env.BUILD_IDENTIFIER }}
          apple-certificate: ${{ secrets.APPLE_CERTIFICATE }}
          apple-certificate-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          apple-identity: ${{ secrets.APPLE_IDENTITY }}
          apple-user-id: ${{ secrets.APPLE_USER_ID }}
          apple-password: ${{ secrets.APPLE_PASSWORD }}
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          gcp-keyring-path: ${{ secrets.GCP_KEYRING_PATH }}
          gcp-key-name: ${{ secrets.GCP_KEY_NAME }}

  deploy-macos-beta:
    name: Publish macOS app (Beta)
    if: ${{ github.event.release.prerelease }}
    runs-on: macos-latest
    environment:
      name: dev
    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6

      - name: 🚀 Deploy macOS app
        uses: ./.github/actions/deploy-macos
        with:
          build-identifier: ${{ env.BUILD_IDENTIFIER }}
          apple-certificate: ${{ secrets.APPLE_CERTIFICATE }}
          apple-certificate-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          apple-identity: ${{ secrets.APPLE_IDENTITY }}
          apple-user-id: ${{ secrets.APPLE_USER_ID }}
          apple-password: ${{ secrets.APPLE_PASSWORD }}
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          gcp-keyring-path: ${{ secrets.GCP_KEYRING_PATH }}
          gcp-key-name: ${{ secrets.GCP_KEY_NAME }}

  deploy-windows-prod:
    name: Publish Windows app
    if: ${{ !github.event.release.prerelease }}
    runs-on: windows-latest
    environment:
      name: prod
    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6

      - name: 🚀 Deploy Windows app
        uses: ./.github/actions/deploy-windows
        with:
          build-identifier: ${{ env.BUILD_IDENTIFIER }}
          gcp-keyring-path: ${{ secrets.GCP_KEYRING_PATH }}
          gcp-key-name: ${{ secrets.GCP_KEY_NAME }}
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

  deploy-windows-beta:
    name: Publish Windows app (Beta)
    if: ${{ github.event.release.prerelease }}
    runs-on: windows-latest
    environment:
      name: dev
    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6

      - name: 🚀 Deploy Windows app
        uses: ./.github/actions/deploy-windows
        with:
          build-identifier: ${{ env.BUILD_IDENTIFIER }}
          gcp-keyring-path: ${{ secrets.GCP_KEYRING_PATH }}
          gcp-key-name: ${{ secrets.GCP_KEY_NAME }}
          identity-provider: ${{ secrets.IDENTITY_PROVIDER }}
          service-account-email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

  upload-release-assets-prod:
    name: Attach release assets
    needs: [deploy-macos-prod, deploy-windows-prod]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6

      - name: 🚀 Attach distributables to release
        uses: ./.github/actions/upload-release-assets
        with:
          release-tag: ${{ github.event.release.tag_name }}

  upload-release-assets-beta:
    name: Attach release assets (Beta)
    needs: [deploy-macos-beta, deploy-windows-beta]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Set up code
        uses: actions/checkout@v6

      - name: 🚀 Attach distributables to release
        uses: ./.github/actions/upload-release-assets
        with:
          release-tag: ${{ github.event.release.tag_name }}

  change-management:
    name: Change management
    needs: [upload-release-assets-prod]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: 🔔 Create deployment notification
        uses: agrc/service-now-worknote-action@v1
        with:
          repo-token: ${{ github.token }}
          username: ${{ secrets.SN_USERNAME }}
          password: ${{ secrets.SN_PASSWORD }}
          instance-name: ${{ secrets.SN_INSTANCE }}
          table-name: ${{ secrets.SN_TABLE }}
          system-id: ${{ secrets.SN_SYS_ID }}

      - name: 💬 Comment on issues in release
        uses: agrc/release-issue-notifications-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
